### ISSUE TITLE
Update FAQ to reflect updated benefits/values

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/todogroup.org#180]
https://todogroup.org/faq/

**Comment by byjrack** [comment]
Starting with random thoughts before moving to a PR to be sure I am on the right page.

Benefits
- Avoid remaking wheels
- Global group of very experienced leads to bounce ideas and ask questions of
- Provide both abstract patterns and specific implementations for Organizations to find something that meshes with their specific needs
- Has representation from very mature Orgs with heavy self-managed or foundation led works all the way to Orgs just talking their first steps in being intentional about their use of OSS
- Engagement from industry partners like Bitergia, GitHub, etc. that help provide commercial bridges 

Like the thread on the Slack there may be a bias in the "deliverables" to running open source works in the FAQ that may be better met to call out what we do around Using and upstream engagement.  My gut says that many new comers to the LF talking about intentional OSS engagement will be doing more in those spaces in the early days versus running their own works.  May be biased from my own experience though.

**Comment by geekygirldawn** [comment]
@byjrack It doesn't look like any of this ever made it to the FAQ, so I'm guessing it got stuck here at the feedback stage? If so, maybe we can tag a few people for feedback?

**Comment by anajsana** [comment]
This is a related PR to update FAQ based on current TODO Group resources and mission: https://github.com/todogroup/todogroup.org/pull/237

**Comment by caniszczyk** [comment]
this has been updated
