### ISSUE TITLE
Finalize guide on outbound open source

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/todogroup.org#219]
This came from TODO Group EU

https://docs.google.com/document/d/1c91nDKueuOH_SFYXQceMkRDsomFesW1GILohJCKQCv4/edit#heading=h.sl8gbpgq9req

**Comment by anajsana** [comment]
I've made some comments to the doc. Overall, I see 3 major action items (suggested in de doc) we can work on to improve this guide:

**Add a clear context to the guide:** This guide is missing some context related to the *type of contributions* organizations can make in open source ecosystems (consuming contributing or releasing)

**Improve structure:** I don't see a clear path to follow when reading this guide. We might want to make the title more homogeneous, using the following structure:

***

MAIN TITLE: Contribution at scale

PART 1: Contributing to existing OSS projects
* Intro
* Why organizations are doing this?
* How are organizations doing this? (guiding principles and procedure)

PART 2: Releasing new OSS projects
* Intro
* Why organizations are doing this?
* How are organizations doing this? (preparation, legal aspects, project governance, tools, etc)

CALL TO ACTION: Aditional resources to get started
***

**Stick to the point:** If we plan to publish this guide at once, readers might get lost because is a lot of different information to digest. I like the idea of creating a guide series whose main title is " Contributing at scale". The first part can be focused on "3rd part contribution" and the second one on "Releasing new projects"

Comments? thoughts? :blush:

**Comment by anajsana** [comment]
The g doc is outdated. We are working with this repo instead: https://github.com/Open-Source-Compliance/outbound-oss

**Comment by anajsana** [comment]
Everything is being managed at https://github.com/Open-Source-Compliance/outbound-oss
