### ISSUE TITLE
TODO Guide Employee Open Source Engagement Guide - Principle 6: Ends Gracefully

### ISSUE THREAD

**Issue by jlprat** [todogroup/todogroup.org#294]
Issue to track progress of the Principle: Ends Gracefully.

**Comment by awright** [comment]
Quotes/Thoughts/BrainDump/etc
- "The most common motivation among open source contributors is to add a feature that they themselves want to see, [[Jeremy Stretch](https://www.linkedin.com/in/jeremy-stretch/)] said. “Once this has been achieved, the contributor rarely sticks around.”" [1]

[1] https://thenewstack.io/how-an-ospo-can-help-your-engineers-give-back-to-open-source/

**Comment by itprofjacobs** [comment]
Adding to reading list for class, thanks! :-)

**Comment by awright** [comment]
Any chance you can pass over the syllabus of readings? Curious to see if
any of your “canon” can also inform a thoughtful guide for corporate
engagement.

**Comment by jlprat** [comment]
Some thoughts:
* **Be open**: Share the expected commitment and involvement in the project. No collaboration is too short, as long as it's well defined upfront
* **Be mindful**: Priorities change, or unexpected things happen, it's fine. Sharing at the earliest possible point in time with the community is crucial. This is true for premature ending and for unexpected extensions

Anything else on my mind on this topic is just circling back to the same things.

**Comment by awright** [comment]
This needs to be revised, but a beginning:

People remember how we leave a room. Our open source endings are a stepping stone to how we enter our next space, whether we return to the same room or enter a new one. Too often well-meaning open source contributors will just disappear, leaving silence and questions in their wake. 

Your endings are just as important as any other juncture in the open source journey. How you choose to close it all out should bring to bear all the principles we’ve been discussing to life. 

See principles 4 and 5 especially. Be transparent and be respectful.  At the onset of engagement, we suggest you share the expected commitment and involvement in the project. At the closure, summarize and share the wrap up. Share where things have gone because no collaboration is too short, as long as it's well defined upfront. And continually defined ongoing.

Be respectful and mindful that things change. Priorities change, or unexpected things happen, it's fine. Sharing at the earliest possible point in time with the community is crucial. This is true for premature ending and for unexpected extensions.
