### ISSUE TITLE
Principle 0: Don't be a Jerk ;)

### ISSUE THREAD

**Issue by awright** [todogroup/todogroup.org#313]
Questions/issue inspired during the 04-13-22 TODO Working Group Call:
- Every projects has a CoC and Contributing Guidelines. How is this different than the social framework of engagement projects articulate here? 
- How does this sit in relationship to such CoC and Contribution covenant? Making something repetitive or superseding existing guidelines is not the intent, so what is the intent?
- Would we ever want this to be something that companies "sign on to" as a commitment to how they intend to engagement with open source communties?

**Comment by awright** [comment]
@jlprat @DuaneOBrien  I think these are very important questions. How does this complement and distinguish itself from existing work. 

@DuaneOBrien do you recall if these principles were based on another template?

**Comment by jwflory** [comment]
Hi, I was asked to comment from working on the [Principles of Authentic Participation](https://authentic-participation.readthedocs.io/). 

> Every projects has a CoC and Contributing Guidelines. How is this different than the social framework of engagement projects articulate here?

A CoC and contributing guidelines usually deal with person-to-person interaction. Contributor to contributor, contributor to maintainer, maintainer to contributor, etc. The Principles approached it from the lens of a larger organization looking to clarify, codify, and cement its open source vision and mission, and how the organization seeks to shape their image in the open source ecosystem.

> How does this sit in relationship to such CoC and Contribution covenant? Making something repetitive or superseding existing guidelines is not the intent, so what is the intent?

It is a type of governance document, similar to a [project charter](https://unicef.github.io/inventory/missions/charters/). The Principles were more an expression of values and vision, stemming from influence of the Free Software movement's similar origin in the 1980s and [why we wanted to work on the Principles](https://authentic-participation.readthedocs.io/advocate-kit/why/).

Since a CoC or other community covenant is rooted in person-to-person interactions, it deals with more practical governance of the project. Something like the Principles focuses (in my mind) more on the high-level vision and how to cement the foundation of a community.

> Would we ever want this to be something that companies "sign on to" as a commitment to how they intend to engagement with open source communties?

The Principles articulated an idealistic vision of how we believed organizations, enterprises, and companies should engage in the open source ecosystem, coming from our group's perspective in the Sustain Summit 2020. Something like the Principles could be adopted as a new commitment, but there should be a sense of how to measure or document adherence to the Principles in order to preserve the authenticity and genuineity of the Principles.

**Comment by alice-sowerby** [comment]
@awright I am looking to close issues associated with this guide so we can publish it and tidy up the repo. Do you consider this issue concluded and OK to close?

**Comment by alice-sowerby** [comment]
Closing due to age of issue and overall agreement in calls that the guide contains what it needs to.
