### ISSUE TITLE
Request to translate TODO Group slides into Chinese on about page

### ISSUE THREAD

**Issue by node** [todogroup/todogroup.org#364]
Hi folks,

After finished OSPO mindmap translation work(https://github.com/todogroup/ospology/pull/276 ), 
I request to translate TODO Group slides (on this page https://todogroup.org/about/ ,the slides actually hosted on https://docs.google.com/presentation/d/1p4dhx0Dg8fZDO8yzp7nWC2r5WHyVH-jjSQM59lkKLdo ) into Chinese, aims to let more developers and organizations learn OSPO best practice.   Hope there will be a reviewer .

**Comment by node** [comment]
I finished translation work now,here is the first version  https://docs.google.com/presentation/d/1ZsVUwtX71v7YfVaqnBqx7fPnhxyiKBZq/edit?usp=sharing&ouid=103350538131971939098&rtpof=true&sd=true

**Comment by node** [comment]
@sunny0826  We cloud use this file in Chinese version.

**Comment by sunny0826** [comment]
@node Is it possible to give me an embedded link, as in: https://docs.google.com/presentation/d/e/2PACX-1vT6TcnSJki1RdzzDTbLCKDl96POVoW4bNZH--0lsJXNrPRRjPC83o2DGKuhZj38qjALnZJPLa0yhMW5/embed?start=false&loop=true&delayms=5000
Otherwise, the effect is now seen like this:
<img width="1364" alt="image" src="https://github.com/todogroup/todogroup.org/assets/24563928/c76ca00a-8fab-4f67-9d5e-a4272b81c778">

**Comment by node** [comment]
@sunny0826 Try this link  https://docs.google.com/presentation/d/1ZsVUwtX71v7YfVaqnBqx7fPnhxyiKBZq/embed?start=false&loop=true&delayms=5000&slide=id.p1

**Comment by sunny0826** [comment]
OK, It's already updated.
